# Generated by Django 4.2.1 on 2025-01-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0003_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.IntegerField(default=1000),
        ),
    ]
