# Generated by Django 4.2.1 on 2025-01-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0004_employee_basic_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=models.IntegerField(default=50000),
        ),
    ]
