# Generated by Django 4.2.1 on 2025-01-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='attendance',
        ),
    ]
