# Generated by Django 4.2.1 on 2025-01-09 13:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_employmenthistory_effective_date'),
        ('attendance_tracking', '0002_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_attendance_per_day'),
        ),
    ]
