# Generated by Django 4.2.1 on 2025-01-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracking', '0003_alter_attendance_date_alter_attendance_employee_and_more'),
    ]

    operations = [
    ]
